### ISSUE TITLE
socket fds are left open if connect fails

### ISSUE THREAD

**Issue by talakoski** [mcfunley/juds#2]
Hi,

nativeOpen() creates a socket file description and tries to connect to server. If the connect fails
an error is rightfully returned but the socket is never closed. The misbehaving code:

    s = socket(PF_UNIX, SOCK_TYPE(jSocketType), 0);
    ASSERTNOERR(s == -1, "nativeOpen: socket");
    ASSERTNOERR(connect(s, (struct sockaddr *)&sa, salen) == -1,
            "nativeOpen: connect");

I fixed it by adding a close statement to the assert but the solution might not open to the casual
reader very easily. A better solution would be appreciated.

    /* close returns either -1 or 0 */
    ASSERTNOERR(connect(s, (struct sockaddr *)&sa, salen) == -1 && close(s) < 1,
            "nativeOpen: connect");

**Comment by phejl** [comment]
This seems to be already fixed...
